(Java) Add 2 Easy array and 1 Medium LinkedList problem solutions
TTUSDC/TTUACM-Algorithms pull request #1
Opened 2019-02-05 19:13 UTC by DrewAMitchell

2019-02-05 22:45 UTC, ynigoreyes requested changes

2019-02-05 22:45 UTC, ynigoreyes commented on Spring_2019/Questions/Medium/OddEvenLinkedList.java
> +            if(head == null) headOCur.next = headEven;
Maybe I am reading this wrong, but on line 20, you already check for a null head. Is this line really in the right place?

2019-02-05 22:45 UTC, ynigoreyes commented on Spring_2019/Questions/Easy/RotateArray.java
> +	public static void main(String[] args) { //Example test case
Please do test cases for all Algorithms submitted. I would suggest you look into a real testing library for Java like JUnit.

2019-02-05 22:45 UTC, ynigoreyes commented on Spring_2019/Questions/Easy/PlusOne.java
> +import java.util.Arrays;
I will submit the Python version of this. I think you may be over complicating this

2019-02-05 22:48 UTC, ynigoreyes commented
For Plus One....


```python
class Solution:
    def plusOne(self, digits):
        multiplier = 1
        ans = 1 # Plus One

        # 127 == 100 + 20 + 7
        
        for i in reversed(digits): # Grab the least significant bit
            ans += (i * multiplier) # Start multiplying
            multiplier *= 10           # Each time we iterate, we increase our multiplier
        
        return list(map(int, str(ans)))
```

2019-02-05 22:49 UTC, ynigoreyes commented
Again, please provide official/proper test cases for all of your algorithms.

2019-02-05 23:15 UTC, DrewAMitchell commented on Spring_2019/Questions/Medium/OddEvenLinkedList.java
> +            if(head == null) headOCur.next = headEven;
Fair point, one of those in-the-moment thoughts. The if check can be bypassed altogether outside the for-loop, given that the problem's preconditions are satisfied (at least 1 node given, non null). Just jumped the gun.

2019-02-05 23:34 UTC, DrewAMitchell commented
The two ideas on my mind for PlusOne were:
Do without string parsing, and follow through with carrying in the case that the digit is 9 (9+1 = 10, a decimal carry).
With that said, it didn't occur to me that you could serialize it into an integer data type, however doing so would require me to have to break it out by way of strings all over again.

TL;DR, the solution I provided doesn't use Strings as an intermediary, but would be much simpler that way.

Also, at initial looks, it seems that your code adds 1 to all number places and also doesn't account for the case when i = 0

2019-02-09 22:29 UTC, ynigoreyes commented
@DrewAMitchell What are we going to do about this PR? Do you want to fix it or use mine?

2019-02-26 17:45 UTC, ynigoreyes approved these changes

2019-02-26 17:45 UTC, merged